name: Handle issues
on: issues

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        env:
          # Carichiamo il JSON qui dentro. GitHub Actions lo gestisce in modo sicuro.
          EVENT_DATA: ${{ toJSON(github.event) }}
          # Ora usiamo la variabile d'ambiente standard di Linux
          run: echo '$EVENT_DATA'

