name: Handle issues
on: issues

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        env:
          EVENT_DATA: ${{ toJSON(github.event) }}
        run: echo "$EVENT_DATA"

